TWEET_NOT_FOUND_ERROR = "Tweet not found"
TWEET_EMPTY_ERROR = "Your tweet is empty"
COMMENT_EMPTY_ERROR = "Your comment is empty"
NOT_LIKEABLE = "This cannot be liked"
NOT_COMMENTABLE = "This cannot be commented"
ALREADY_LIKED_ERROR = "You already like this"
GENERIC_ERROR = "An error occured"
