TWEET_NOT_FOUND_ERROR = "Tweet not found"
TWEET_EMPTY_ERROR = "Your tweet is empty"
COMMENT_EMPTY_ERROR = "Your comment is empty"
NOT_LIKEABLE = "This cannot be liked"
GENERIC_ERROR = "An error occured"
